### ISSUE TITLE
Chaves estão fora do padrão

### ISSUE THREAD

**Issue by vcapretz** [ZXVentures/code-challenge#1]
O modelo de um objeto de PDV em https://github.com/ZXVentures/code-challenge/blob/master/backend.md#sobre-o-desafio mostra as chaves em formato camelCase, enquanto o JSON https://github.com/ZXVentures/code-challenge/blob/master/files/pdvs.json com dados de exemplo exibe-as em snake_case. 

As chaves devem estar em qual dos dois formatos?

**Comment by leocadastro** [comment]
Muito obrigado @vcapretz .

O ideal seria que o json estivesse em camelCase.

Vamos corrigir =)

Obrigado!

**Comment by leocadastro** [comment]
corrigido
