### ISSUE TITLE
Maybe we should add a section informing the candidate that the optimal time for finishing the test is _a week_ but that the candidate is allowed to ask for more time without any penalties

### ISSUE THREAD

**Issue by flpStrri** [ZXVentures/code-challenge#21]
From our Townhall meeting: Maybe we should add a section informing the candidate that the optimal time for finishing the test is _a week_ but that the candidate is allowed to ask for more time without any penalties

_Originally posted by @rodrigobotti in https://github.com/ZXVentures/ze-code-challenges/pull/16#issuecomment-649003029_

**Comment by flpStrri** [comment]
@ZXVentures/ze-delivery, this should stay at the "root" README.md?

When we send the code challenge to the candidate we send the specific `.md` or we send him to `https://github.com/ZXVentures/ze-code-challenges`?

**Comment by askmon** [comment]
@flpStrri what we send is this link: https://github.com/ZXVentures/code-challenge/blob/master/backend.md (at least this was the one I received)

**Comment by flpStrri** [comment]
So we need to add this info in all `.md`s. :/
